spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flow_task_manager?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: dombimihaly89
    password: Dina*Maki0307
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: 'create-drop'
